# Generated by Django 3.2.6 on 2021-08-21 10:50

import authinticator.utilities
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=263)),
                ('descreption', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='%Y/%m/%d')),
                ('url', models.URLField(max_length=1023)),
                ('developers', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('project_manager', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='manager', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('solved', models.BooleanField(default=False)),
                ('solution_time', models.DateTimeField(blank=True, null=True)),
                ('body', models.TextField()),
                ('title', models.CharField(max_length=263)),
                ('owner', models.ForeignKey(default=0, on_delete=models.SET(authinticator.utilities.get_sentinel_user), to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operation.project')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('body', models.TextField()),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operation.ticket')),
                ('replies_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operation.comment')),
                ('solution_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solution', to='operation.ticket')),
            ],
        ),
    ]
