# Generated by Django 3.2.6 on 2021-08-23 07:38

import authinticator.utilities
from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('operation', '0003_alter_comment_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='Priority',
            field=models.CharField(choices=[('L', 'low'), ('M', 'medium'), ('H', 'high')], default='L', max_length=1),
        ),
        migrations.AddField(
            model_name='ticket',
            name='assigned_developer',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET(authinticator.utilities.get_sentinel_user), related_name='assigned_tickets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ticket',
            name='kind',
            field=models.CharField(choices=[('Q', 'question'), ('I', 'Issue'), ('B', 'bug'), ('D', 'idea'), ('F', 'feature wanted')], default='Q', max_length=1),
        ),
        migrations.AddField(
            model_name='ticket',
            name='last_update',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('N', 'new'), ('I', 'in progress'), ('U', 'updated'), ('R', 'resolved')], default='N', max_length=1),
        ),
    ]
