# Generated by Django 3.2.6 on 2021-08-17 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authinticator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, upload_to='%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='solution_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
