# Generated by Django 3.2.6 on 2021-08-17 14:45

import authinticator.utilities
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authinticator', '0007_alter_ticket_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='owner',
            field=models.ForeignKey(default=0, on_delete=models.SET(authinticator.utilities.get_sentinel_user), to=settings.AUTH_USER_MODEL),
        ),
    ]
