# Generated by Django 3.2.6 on 2021-08-24 16:11

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authinticator', '0011_auto_20210824_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, storage=django.core.files.storage.FileSystemStorage(location='/home/abdo/Documents/pyweb/dj_web/bug_tracking/bug_trackingts/media/profile'), upload_to='profils/%Y/%m/%d '),
        ),
    ]
